import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/atoms/Navbar";
import CardContainer from "@/components/CardContainer/CardContainer";
import { useTheme } from "@/contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { theme, toggleTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Navbar>
          <button onClick={toggleTheme}>{theme}</button>
        </Navbar>
        <CardContainer />
      </main>
    </>
  );
}
